[package]
name = "plugin-test-main"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
build = "build.rs"

[dependencies]
plugin-test-api = { version = "^0.1", paths = "../plugin-test-api" }
plugin-test-plugins = { version = "^0.1", paths = "../plugins" }
